# Generated by Django 6.0.3 on 2026-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_place_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('history', models.TextField()),
                ('culture', models.TextField()),
                ('food', models.TextField()),
                ('etiquette', models.TextField()),
                ('languages', models.TextField()),
                ('phrases', models.TextField()),
                ('folklore', models.TextField()),
            ],
        ),
    ]
